//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRNOW_LAST_HOUR
    {
        public string AIRNOW_ORG { get; set; }
        public string AIRNOW_SITE { get; set; }
        public string DATA_STATUS { get; set; }
        public string DT { get; set; }
        public string PAR_CODE { get; set; }
        public string DATA_VALUE { get; set; }
        public string UNIT_CODE { get; set; }
        public int POC { get; set; }
    }
}
