//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITOR_SNAPSHOT
    {
        public System.Guid MONITOR_IDX { get; set; }
        public Nullable<System.DateTime> POLLING_LAST_RUN_DT { get; set; }
        public Nullable<System.DateTime> lvl1 { get; set; }
        public Nullable<System.DateTime> lvl2 { get; set; }
    }
}
