//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTHLY_USAGE_FIVEMIN
    {
        public int YR { get; set; }
        public int MN { get; set; }
        public Nullable<int> CNT { get; set; }
    }
}
