//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QRESTEntities : DbContext
    {
        public QRESTEntities()
            : base("name=QRESTEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_QREST_APP_SETTINGS> T_QREST_APP_SETTINGS { get; set; }
        public virtual DbSet<T_QREST_APP_SETTINGS_CUSTOM> T_QREST_APP_SETTINGS_CUSTOM { get; set; }
        public virtual DbSet<T_QREST_APP_TASKS> T_QREST_APP_TASKS { get; set; }
        public virtual DbSet<T_QREST_EMAIL_TEMPLATE> T_QREST_EMAIL_TEMPLATE { get; set; }
        public virtual DbSet<T_QREST_HELP_DOCS> T_QREST_HELP_DOCS { get; set; }
        public virtual DbSet<T_QREST_ORG_EMAIL_RULE> T_QREST_ORG_EMAIL_RULE { get; set; }
        public virtual DbSet<T_QREST_ORG_USERS> T_QREST_ORG_USERS { get; set; }
        public virtual DbSet<T_QREST_ORGANIZATIONS> T_QREST_ORGANIZATIONS { get; set; }
        public virtual DbSet<T_QREST_QC_ASSESSMENT> T_QREST_QC_ASSESSMENT { get; set; }
        public virtual DbSet<T_QREST_REF_AQS_AGENCY> T_QREST_REF_AQS_AGENCY { get; set; }
        public virtual DbSet<T_QREST_REF_ASSESS_TYPE> T_QREST_REF_ASSESS_TYPE { get; set; }
        public virtual DbSet<T_QREST_REF_COUNTY> T_QREST_REF_COUNTY { get; set; }
        public virtual DbSet<T_QREST_REF_DURATION> T_QREST_REF_DURATION { get; set; }
        public virtual DbSet<T_QREST_REF_PAR_METHODS> T_QREST_REF_PAR_METHODS { get; set; }
        public virtual DbSet<T_QREST_REF_PARAMETERS> T_QREST_REF_PARAMETERS { get; set; }
        public virtual DbSet<T_QREST_REF_REGION> T_QREST_REF_REGION { get; set; }
        public virtual DbSet<T_QREST_REF_STATE> T_QREST_REF_STATE { get; set; }
        public virtual DbSet<T_QREST_REF_UNITS> T_QREST_REF_UNITS { get; set; }
        public virtual DbSet<T_QREST_ROLES> T_QREST_ROLES { get; set; }
        public virtual DbSet<T_QREST_SITE_NOTIFY> T_QREST_SITE_NOTIFY { get; set; }
        public virtual DbSet<T_QREST_SITE_POLL_CONFIG> T_QREST_SITE_POLL_CONFIG { get; set; }
        public virtual DbSet<T_QREST_SITE_POLL_CONFIG_DTL> T_QREST_SITE_POLL_CONFIG_DTL { get; set; }
        public virtual DbSet<T_QREST_SITES> T_QREST_SITES { get; set; }
        public virtual DbSet<T_QREST_SYS_LOG> T_QREST_SYS_LOG { get; set; }
        public virtual DbSet<T_QREST_SYS_LOG_ACTIVITY> T_QREST_SYS_LOG_ACTIVITY { get; set; }
        public virtual DbSet<T_QREST_SYS_LOG_EMAIL> T_QREST_SYS_LOG_EMAIL { get; set; }
        public virtual DbSet<T_QREST_USER_CLAIMS> T_QREST_USER_CLAIMS { get; set; }
        public virtual DbSet<T_QREST_USER_LOGINS> T_QREST_USER_LOGINS { get; set; }
        public virtual DbSet<T_QREST_USER_NOTIFICATION> T_QREST_USER_NOTIFICATION { get; set; }
        public virtual DbSet<T_QREST_USERS> T_QREST_USERS { get; set; }
        public virtual DbSet<T_QREST_MONITORS> T_QREST_MONITORS { get; set; }
        public virtual DbSet<T_QREST_REF_COLLECT_FREQ> T_QREST_REF_COLLECT_FREQ { get; set; }
        public virtual DbSet<T_QREST_REF_PAR_UNITS> T_QREST_REF_PAR_UNITS { get; set; }
        public virtual DbSet<T_QREST_DATA_FIVE_MIN> T_QREST_DATA_FIVE_MIN { get; set; }
        public virtual DbSet<T_QREST_REF_TIMEZONE> T_QREST_REF_TIMEZONE { get; set; }
        public virtual DbSet<T_QREST_DATA_HOURLY> T_QREST_DATA_HOURLY { get; set; }
    }
}
