//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE_HEALTH
    {
        public string ORG_ID { get; set; }
        public System.Guid SITE_IDX { get; set; }
        public string SITE_ID { get; set; }
        public string SITE_NAME { get; set; }
        public Nullable<bool> POLLING_ONLINE_IND { get; set; }
        public Nullable<System.DateTime> POLLING_LAST_RUN_DT { get; set; }
        public Nullable<System.DateTime> POLLING_NEXT_RUN_DT { get; set; }
        public Nullable<bool> AIRNOW_IND { get; set; }
        public string AIRNOW_USR { get; set; }
        public string AIRNOW_PWD { get; set; }
        public string AIRNOW_ORG { get; set; }
        public string AIRNOW_SITE { get; set; }
        public string LOGGER_TYPE { get; set; }
        public string TIME_POLL_TYPE { get; set; }
        public string RAW_DURATION_CODE { get; set; }
        public Nullable<System.DateTime> LAST_UTC_POLL { get; set; }
        public System.DateTime CURR_UTC { get; set; }
    }
}
