//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_TRAIN_LESSON_STEP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_QREST_TRAIN_LESSON_STEP()
        {
            this.T_QREST_TRAIN_LESSON_STEP_USER = new HashSet<T_QREST_TRAIN_LESSON_STEP_USER>();
        }
    
        public System.Guid LESSON_STEP_IDX { get; set; }
        public System.Guid LESSON_IDX { get; set; }
        public Nullable<int> LESSON_STEP_SEQ { get; set; }
        public string LESSON_STEP_DESC { get; set; }
        public string REQUIRED_URL { get; set; }
        public Nullable<bool> REQ_CONFIRM { get; set; }
        public string REQUIRED_YT_VID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QREST_TRAIN_LESSON_STEP_USER> T_QREST_TRAIN_LESSON_STEP_USER { get; set; }
    }
}
