//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_REF_PAR_METHODS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_QREST_REF_PAR_METHODS()
        {
            this.T_QREST_MONITORS = new HashSet<T_QREST_MONITORS>();
        }
    
        public System.Guid PAR_METHOD_IDX { get; set; }
        public string PAR_CODE { get; set; }
        public string METHOD_CODE { get; set; }
        public string RECORDING_MODE { get; set; }
        public string COLLECTION_DESC { get; set; }
        public string ANALYSIS_DESC { get; set; }
        public string REFERENCE_METHOD_ID { get; set; }
        public string EQUIVALENT_METHOD { get; set; }
        public string STD_UNIT_CODE { get; set; }
        public Nullable<double> FED_MDL { get; set; }
        public Nullable<double> MIN_VALUE { get; set; }
        public Nullable<double> MAX_VALUE { get; set; }
        public bool ACT_IND { get; set; }
        public string CREATE_USER_IDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string MODIFY_USER_IDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QREST_MONITORS> T_QREST_MONITORS { get; set; }
        public virtual T_QREST_REF_PARAMETERS T_QREST_REF_PARAMETERS { get; set; }
        public virtual T_QREST_REF_UNITS T_QREST_REF_UNITS { get; set; }
    }
}
