//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_HELP_DOCS
    {
        public int HELP_IDX { get; set; }
        public string HELP_TITLE { get; set; }
        public string HELP_HTML { get; set; }
        public int SORT_SEQ { get; set; }
    }
}
