//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_SYS_LOG
    {
        public int LOG_ID { get; set; }
        public Nullable<System.DateTime> LOG_DT { get; set; }
        public string LOG_TYP { get; set; }
        public string LOG_USERID { get; set; }
        public string LOG_MSG { get; set; }
        public string APP_ID { get; set; }
    }
}
