//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_ASSESS_DOCS
    {
        public System.Guid ASSESS_DOC_IDX { get; set; }
        public System.Guid SITE_IDX { get; set; }
        public Nullable<System.Guid> MONITOR_IDX { get; set; }
        public byte[] DOC_CONTENT { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_TYPE { get; set; }
        public string DOC_FILE_TYPE { get; set; }
        public Nullable<int> DOC_SIZE { get; set; }
        public string DOC_COMMENT { get; set; }
        public string DOC_AUTHOR { get; set; }
        public string CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public Nullable<System.DateTime> START_DT { get; set; }
        public Nullable<System.DateTime> END_DT { get; set; }
    
        public virtual T_QREST_MONITORS T_QREST_MONITORS { get; set; }
        public virtual T_QREST_SITES T_QREST_SITES { get; set; }
    }
}
