//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_TRAIN_LESSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_QREST_TRAIN_LESSON()
        {
            this.T_QREST_TRAIN_COURSE_LESSON = new HashSet<T_QREST_TRAIN_COURSE_LESSON>();
            this.T_QREST_TRAIN_LESSON_USER = new HashSet<T_QREST_TRAIN_LESSON_USER>();
        }
    
        public System.Guid LESSON_IDX { get; set; }
        public string LESSON_TITLE { get; set; }
        public string LESSON_DESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QREST_TRAIN_COURSE_LESSON> T_QREST_TRAIN_COURSE_LESSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QREST_TRAIN_LESSON_USER> T_QREST_TRAIN_LESSON_USER { get; set; }
    }
}
