//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_USER_NOTIFICATION
    {
        public System.Guid NOTIFICATION_IDX { get; set; }
        public string USER_IDX { get; set; }
        public System.DateTime NOTIFY_DT { get; set; }
        public string NOTIFY_TYPE { get; set; }
        public string NOTIFY_TITLE { get; set; }
        public string NOTIFY_DESC { get; set; }
        public Nullable<bool> READ_IND { get; set; }
        public string FROM_USER_IDX { get; set; }
        public string CREATE_USERIDX { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    }
}
