//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_REF_QC
    {
        public string PAR_CODE { get; set; }
        public string ASSESSMENT_TYPE { get; set; }
        public Nullable<double> AMT_DIFF_LIM { get; set; }
        public Nullable<double> PCT_DIFF_LIM { get; set; }
        public Nullable<double> MIN_CONC { get; set; }
        public Nullable<double> MAX_CONC { get; set; }
    }
}
