//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_TRAIN_COURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_QREST_TRAIN_COURSE()
        {
            this.T_QREST_TRAIN_COURSE_LESSON = new HashSet<T_QREST_TRAIN_COURSE_LESSON>();
            this.T_QREST_TRAIN_COURSE_USER = new HashSet<T_QREST_TRAIN_COURSE_USER>();
        }
    
        public System.Guid COURSE_IDX { get; set; }
        public string COURSE_NAME { get; set; }
        public string COURSE_DESC { get; set; }
        public Nullable<int> COURSE_SEQ { get; set; }
        public bool ACT_IND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QREST_TRAIN_COURSE_LESSON> T_QREST_TRAIN_COURSE_LESSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QREST_TRAIN_COURSE_USER> T_QREST_TRAIN_COURSE_USER { get; set; }
    }
}
