//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_REF_COUNTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_QREST_REF_COUNTY()
        {
            this.T_QREST_SITES = new HashSet<T_QREST_SITES>();
        }
    
        public string STATE_CD { get; set; }
        public string COUNTY_CD { get; set; }
        public string COUNTY_NAME { get; set; }
    
        public virtual T_QREST_REF_STATE T_QREST_REF_STATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QREST_SITES> T_QREST_SITES { get; set; }
    }
}
