//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_SITE_NOTIFY
    {
        public System.Guid SITE_NOTIFY_IDX { get; set; }
        public System.Guid SITE_IDX { get; set; }
        public string NOTIFY_USER_IDX { get; set; }
        public string MODIFY_USER_IDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        public virtual T_QREST_SITES T_QREST_SITES { get; set; }
        public virtual T_QREST_USERS T_QREST_USERS { get; set; }
    }
}
