//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_SYS_LOG_EMAIL
    {
        public int LOG_EMAIL_ID { get; set; }
        public Nullable<System.DateTime> EMAIL_DT { get; set; }
        public string EMAIL_FROM { get; set; }
        public string EMAIL_TO { get; set; }
        public string EMAIL_CC { get; set; }
        public string EMAIL_SUBJ { get; set; }
        public string EMAIL_MSG { get; set; }
        public string EMAIL_TYPE { get; set; }
        public string APP_ID { get; set; }
    }
}
