//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_DATA_HOURLY_LOG
    {
        public System.Guid DATA_HOURLY_LOG_IDX { get; set; }
        public System.Guid DATA_HOURLY_IDX { get; set; }
        public string NOTES { get; set; }
        public string MODIFY_USERIDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    
        public virtual T_QREST_DATA_HOURLY T_QREST_DATA_HOURLY { get; set; }
    }
}
