//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_REF_QC_AUDIT_LVL
    {
        public string PAR_CODE { get; set; }
        public int AUDIT_LVL { get; set; }
        public Nullable<double> MIN_AMT { get; set; }
        public Nullable<double> MAX_AMT { get; set; }
    }
}
