//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_DATA_IMPORT_TEMP
    {
        public System.Guid DATA_IMPORT_TEMP_IDX { get; set; }
        public string IMPORT_USER_IDX { get; set; }
        public Nullable<System.Guid> DATA_ORIG_TABLE_IDX { get; set; }
        public System.Guid MONITOR_IDX { get; set; }
        public Nullable<System.DateTime> DATA_DTTM_UTC { get; set; }
        public Nullable<System.DateTime> DATA_DTTM_LOCAL { get; set; }
        public string DATA_VALUE { get; set; }
        public Nullable<decimal> DATA_VALUE_NUM { get; set; }
        public string UNIT_CODE { get; set; }
        public string VAL_CD { get; set; }
        public string AQS_NULL_CODE { get; set; }
        public string AQS_QUAL_CODES { get; set; }
        public Nullable<System.Guid> IMPORT_IDX { get; set; }
        public Nullable<System.DateTime> IMPORT_DT { get; set; }
        public Nullable<bool> IMPORT_VAL_IND { get; set; }
        public Nullable<bool> IMPORT_DUP_IND { get; set; }
        public string IMPORT_MSG { get; set; }
    
        public virtual T_QREST_DATA_IMPORTS T_QREST_DATA_IMPORTS { get; set; }
    }
}
