//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRESTModel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_SNAPSHOT
    {
        public string USER_IDX { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public System.Guid COURSE_IDX { get; set; }
        public string COURSE_NAME { get; set; }
        public Nullable<int> TotalCourseSteps { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<int> StepsCompleted { get; set; }
        public Nullable<int> CertIssuedInd { get; set; }
        public Nullable<System.DateTime> CertIssuedDate { get; set; }
        public string ORG_NAME { get; set; }
    }
}
