CREATE TABLE [T_QREST_QC_ASSESSMENT_DTL] (
	[QC_ASSESS_DTL_IDX] UNIQUEIDENTIFIER NOT NULL,
	[QC_ASSESS_IDX] UNIQUEIDENTIFIER NOT NULL,
	[MON_CONCENTRATION] [float],
	[ASSESS_KNOWN_CONCENTRATION] [float],
	[AQS_NULL_CODE] [varchar](2) NULL,
	[COMMENTS] [varchar](100) NULL,
	[CREATE_USER_IDX] nvarchar(128),
	[CREATE_DT] datetime2(0),
	[MODIFY_USER_IDX] nvarchar(128),
	[MODIFY_DT] datetime2(0),
    CONSTRAINT [PK_T_QREST_QC_ASSESSMENT_DTL] PRIMARY KEY ([QC_ASSESS_DTL_IDX]),
    CONSTRAINT [FK_T_QREST_QC_ASSESSMENT_DTL_A] FOREIGN KEY ([QC_ASSESS_IDX]) REFERENCES [T_QREST_QC_ASSESSMENT] ([QC_ASSESS_IDX]) ON DELETE CASCADE
);


ALTER TABLE [T_QREST_DATA_FIVE_MIN] ADD [DATA_DTTM_LOCAL] datetime2(0);

ALTER TABLE [T_QREST_HELP_DOCS] ADD [HELP_CAT] varchar(50);

ALTER TABLE [T_QREST_QC_ASSESSMENT] ADD [ASSESSMENT_TM] varchar(10);