INSERT INTO T_QREST_APP_SETTINGS ([SETTING_NAME],[SETTING_VALUE],[SETTING_DESC],[MODIFY_USER_IDX],[MODIFY_DT],ENCRYPT_IND) VALUES ('CDX_URL','change.me','Website URL for the Exchange Network Node (CDX).','',GetDate(),0);
INSERT INTO T_QREST_APP_SETTINGS ([SETTING_NAME],[SETTING_VALUE],[SETTING_DESC],[MODIFY_USER_IDX],[MODIFY_DT],ENCRYPT_IND) VALUES ('CDX_GLOBAL_USER','change.me','Exchange Network username, if none supplied by tribe.','',GetDate(),0);
INSERT INTO T_QREST_APP_SETTINGS ([SETTING_NAME],[SETTING_VALUE],[SETTING_DESC],[MODIFY_USER_IDX],[MODIFY_DT],ENCRYPT_IND) VALUES ('CDX_GLOBAL_PWD','change.me','Exchange Network password, if none supplied by tribe.','',GetDate(),1);
INSERT INTO T_QREST_APP_SETTINGS ([SETTING_NAME],[SETTING_VALUE],[SETTING_DESC],[MODIFY_USER_IDX],[MODIFY_DT],ENCRYPT_IND) VALUES ('AIRNOW_ACTIVE_IND','1','Set to 1 to globally allow AirNow service','',GetDate(),0);


ALTER TABLE [T_QREST_ORGANIZATIONS] ADD [AQS_AQS_UID] varchar(100);
ALTER TABLE [T_QREST_ORGANIZATIONS] ADD [AQS_AQS_SCREENING_GRP] varchar(100);

ALTER TABLE [T_QREST_SYS_LOG_ACTIVITY] ALTER COLUMN [ACTIVITY_DESC] [varchar](2000) NULL;

ALTER TABLE [T_QREST_AQS] ADD [CDX_TOKEN] [varchar](250);
ALTER TABLE [T_QREST_AQS] ADD [DOWNLOAD_FILE] [varbinary](max);


GO

CREATE TABLE [dbo].[T_QREST_DATA_HOURLY_LOG](
	[DATA_HOURLY_LOG_IDX] [uniqueidentifier] NOT NULL,
	[DATA_HOURLY_IDX] [uniqueidentifier] NOT NULL,
	[NOTES] varchar(100) NULL,
	[MODIFY_USERIDX] nvarchar(128) NULL,
	[MODIFY_DT] [datetime2](0) NULL,
 CONSTRAINT [PK_T_QREST_DATA_HOURLY_LOG] PRIMARY KEY CLUSTERED ([DATA_HOURLY_LOG_IDX] ASC),
 CONSTRAINT [FK_T_QREST_DATA_HOURLY_LOG_O] FOREIGN KEY ([DATA_HOURLY_IDX]) REFERENCES [T_QREST_DATA_HOURLY] ([DATA_HOURLY_IDX]) ON DELETE CASCADE
) ON [PRIMARY]
GO



ALTER TABLE [T_QREST_ASSESS_DOCS] ADD [START_DT] datetime2(0);
ALTER TABLE [T_QREST_ASSESS_DOCS] ADD [END_DT] datetime2(0);
ALTER TABLE [T_QREST_ASSESS_DOCS] DROP COLUMN YR;
ALTER TABLE [T_QREST_ASSESS_DOCS] DROP COLUMN MON;
