//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QREST.App_Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_EMAIL_TEMPLATE
    {
        public int EMAIL_TEMPLATE_ID { get; set; }
        public string EMAIL_TEMPLATE_NAME { get; set; }
        public string EMAIL_TEMPLATE_DESC { get; set; }
        public string SUBJ { get; set; }
        public string MSG { get; set; }
        public string MODIFY_USER_IDX { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
    }
}
