//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QREST.App_Logic.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QREST_SYS_LOG_ACTIVITY
    {
        public int LOG_ACTIVITY_IDX { get; set; }
        public Nullable<System.DateTime> ACTIVITY_DT { get; set; }
        public string ACTIVITY_TYPE { get; set; }
        public string ACTIVITY_USER { get; set; }
        public string ACTIVITY_DESC { get; set; }
        public string IP_ADDRESS { get; set; }
    }
}
